name: Maven Tests & JaCoCo Coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"

    - name: Run tests
      run: mvn -B clean test

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload JaCoCo HTML report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/
